name: Build Android APK

on:
  push:
    branches: [main]  # or dev, or whatever
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Setup Expo CLI
        run: npm install -g expo-cli

      - name: Setup EAS CLI
        run: npm install -g eas-cli

      - name: Authenticate with Expo
        uses: expo/expo-github-action@v8
        with:
          token: ${{ secrets.EXPO_TOKEN }}
          expo-cache: true
          eas-cache: true

      - name: Build Android APK
        run: eas build --platform android --profile production --non-interactive
